sudo: true
env:
  AIRFLOW_HOME=$TRAVIS_BUILD_DIR/airflow
os: linux
dist: trusty
language: python
cache:
  - pip
services:
  - docker
  - postgresql
python:
  - "2.7"
  - "3.6"
git:
  depth: false
jobs:
  include:
    -stage: tagger
      install: pip install tox
      script: cd api/tagger && tox
      after_success:
        - codecov
    - stage: airflow
      name: linting
      install: pip install flake8
      script: flake8 ./airflow ./tests
    - script: 
      - sudo pip install -r airflow/requirements.txt
      - sudo service postgresql stop
      - sudo make install
    name: install  
