sudo: true
env:
  AIRFLOW_HOME=$TRAVIS_BUILD_DIR/airflow
language: python
cache:
  - pip
services:
  - docker
  - postgresql
python:
  - "2.7"
  - "3.6"
git:
  depth: false
install: sudo pip install flake8 tox
script:
  - tox --workdir=$TRAVIS_BUILD_DIR/api/tagger
  - flake8 ./airflow
  - sudo service postgresql stop
  - sudo make install
