sudo: true
env:
  AIRFLOW_HOME=$TRAVIS_BUILD_DIR/airflow
os: linux
dist: trusty
language: python
cache:
  - pip
services:
  - docker
  - postgresql
python:
  - "3.6"
git:
  depth: false
jobs:
  include:
    - stage: linting
      install: pip install flake8
      script: flake8 ./airflow ./tests
    - stage: tagger
      install:   
        - pip uninstall -y six
        - pip install six>=1.11.0
      script:
        - cd api/tagger
        - sudo pip install -r requirements.txt
        - python -m spacy download en
        - python -m pytest --cov=. tests
        - codecov
    - stage: airflow_install
      script: 
        - sudo pip install -r airflow/requirements.txt
        - sudo service postgresql stop
        - sudo make install
stages:
  - linting
  - tagger
  - airflow_install
