sudo: true
env:
  AIRFLOW_HOME=$TRAVIS_BUILD_DIR/airflow
language: python
cache:
  - pip
services:
  - docker
  - postgresql
python:
  - "3.6"
git:
  depth: false
before_install:
  - psql -U postgres -c "CREATE USER airflow WITH PASSWORD 'airflow'"
  - psql -U postgres -c "CREATE DATABASE airflow"
install:
  - "sudo pip install -r requirements-dev.txt"
jobs:
  include:
    - stage: linting
      install: pip install flake8
      script: flake8 ./airflow ./tests
    - stage: integrity_tests_airflow
      script:
        - airflow initdb
        - coverage run -m pytest tests/airflow/integrity_tests/*
        - codecov
    - stage: install
      script: 
        - sudo service postgresql stop
        - sudo make install
    - stage: run
      script:
        - sudo service postgresql stop
        - sudo make run
stages:
  - linting
  - integrity_tests_airflow
  - install
  - run