sudo: true
env:
  AIRFLOW_HOME=$TRAVIS_BUILD_DIR/airflow
os: linux
dist: trusty
language: python
cache:
  - pip
services:
  - docker
  - postgresql
python:
  - "2.7"
  - "3.6"
git:
  depth: false
jobs:
  include:
    - stage: linting
      install: pip install flake8
      script: flake8 ./airflow ./tests
    - stage: tagger
      python: "2.7"
      install:   
        - sudo pip install -r api/tagger/requirements.txt
        - python -m spacy download en
      script:
        - python -m pytest --cov=api/tagger/tests api/tagger/tests
        - codecov
      after_success:
        - codecov
    - stage: airflow_install
      script: 
        - sudo pip install -r airflow/requirements.txt
        - sudo service postgresql stop
        - sudo make install
stages:
  - linting
  - tagger
  - airflow_install
