sudo: true
env:
  AIRFLOW_HOME=$TRAVIS_BUILD_DIR/airflow
os: linux
dist: trusty
language: python
cache:
  - pip
services:
  - docker
  - postgresql
python:
  - "2.7"
  - "3.6"
git:
  depth: false
install: pip install tox flake8

script: cd api/tagger && tox
name: tagger
after_success:
  - codecov

script: flake8 ./airflow ./tests
name: linting

script: 
  - sudo pip install -r airflow/requirements.txt
  - sudo service postgresql stop
  - sudo make install
name: install  
