sudo: true
env:
  AIRFLOW_HOME=$TRAVIS_BUILD_DIR/airflow
os: linux
dist: trusty
language: python
cache:
  - pip
services:
  - docker
  - postgresql
python:
  - "2.7"
  - "3.6"
git:
  depth: false
install: pip install tox flake8
job:
  include:
  -stage: tagger
    script: cd api/tagger && tox
    after_success:
      - codecov
  -stage: airflow
    script: flake8 ./airflow ./tests
    name: linting
    script: 
      - sudo pip install -r airflow/requirements.txt
      - sudo service postgresql stop
      - sudo make install
    name: install  
