env:
  AIRFLOW_HOME=$TRAVIS_BUILD_DIR/airflow
language: python
python:
  - "3.6"
git:
  depth: false
install:
  - "pip install -r requirements.txt"
jobs:
  include:
    stage: integrity_tests_airflow
    script:
        - airflow initdb
        - coverage run -m pytest tests/airflow/integrity_tests/*
