Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/vagrant"

  #Connect server mongo to localhost
  config.vm.network :forwarded_port, guest: 27017, host: 27017

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.name = "dev"
  end

#Python env installation
$python = <<SCRIPT
    echo Installing python, packages...
    sudo apt-get update
    sudo apt-get install -y python-virtualenv virtualenvwrapper git \
        mercurial build-essential python-dev zlib1g-dev \
        zlib1g zlibc libtool libffi-dev libssl-dev libpq-dev libgeoip-dev \
        libxml2-dev libxslt1-dev libbz2-dev libsqlite3-dev libreadline-dev \
        libjpeg-dev
    echo "Configuring virtualenvwrapper ..."
    printf '\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n' 'export PIP_REQUIRE_VIRTUALENV=true' \
        'export WORKON_HOME=/vagrant/.virtualenvs' \
        'export PROJECT_HOME=/vagrant' \
        'export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python' \
        'export VIRTUALENVWRAPPER_VIRTUALENV=/usr/bin/virtualenv' \
        'source /usr/share/virtualenvwrapper/virtualenvwrapper.sh' >> /home/vagrant/.bashrc
    source /home/vagrant/.bashrc
SCRIPT

#Ansible installation
$ansible = <<SCRIPT
  echo "Installing Ansible..."
  apt-get install -y software-properties-common
  apt-add-repository ppa:ansible/ansible
  apt-get update
  apt-get install -y --force-yes ansible
SCRIPT

  config.vm.provision "shell", inline: $ansible
  config.vm.provision "shell", inline: $python
  config.vm.provision "shell", inline: 'ansible-playbook /vagrant/ansible/dev.yml -c local'
  
end
